version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY: node-api
    ECS_CONTAINER_NAME: node3
phases:
  pre_build:
    commands:
      - ECR_REPO_URL=$(aws ecr describe-repositories --repository-names $ECR_REPOSITORY --region $AWS_DEFAULT_REGION --query 'repositories[0].repositoryUri' --output text)
      - IMAGE_TAG=$(cat /proc/sys/kernel/random/uuid)
      - echo $ECR_REPO_URL:$IMAGE_TAG
  build:
    commands:
      - docker build -t $ECR_REPO_URL:$IMAGE_TAG .
      - docker push $ECR_REPO_URL:$IMAGE_TAG
  post_build:
    commands:
      - LOGIN_CMD=$(aws ecr get-login-password --region $AWS_DEFAULT_REGION)
      - echo $LOGIN_CMD | docker login --username AWS --password-stdin $ECR_REPO_URL
      - echo Writing image definitions file...
      - printf '[{"name":"'$ECS_CONTAINER_NAME'","imageUri":"%s"}]' $ECR_REPO_URL:$IMAGE_TAG > imagedefinitions.json

artifacts:
    files: imagedefinitions.json    

