version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    ECR_REPOSITORY: node-api
    ECR_REPO_URL: $ecr_uri
phases:
  build:
    commands:
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 945952216210.dkr.ecr.us-east-1.amazonaws.com
      - IMAGE_TAG=$(cat /proc/sys/kernel/random/uuid)
      - echo $ECR_REPO_URL:$IMAGE_TAG
      # - docker build -t $ECR_REPO_URL:$IMAGE_TAG .
      # - docker push $ECR_REPO_URL:$IMAGE_TAG
    
# artifacts:
    # files: imagedefinitions.json
